version: '2'

services:
  gapi:
    image: coffee_coffee:latest
    volumes:
      - google:/usr/src/app
  gcloud:
    build:
      context: .
      dockerfile: Dockerfile-gcloud
    volumes:
      - gcloud:/.config
      - repo:/default
volumes:
  google:
    driver: local
  gcloud:
    driver: local
  repo:
    driver: local