version: "2"

services:
  consul:
    image: consul:v0.7.0
    ports:
      - 8500:8500
    restart: unless-stopped
  vault:
    image: vault:0.6.1
    ports:
      - 8200:8200
    restart: unless-stopped
    cap_add:
      - IPC_LOCK  # prevent memory from swapping to disk
    volumes:
      - "./vault/config:/vault/config"
    command: >-
      server
  names:
    build:
      context: ./names
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      - "DOMAIN=swim"
      - "IP=192.168.99.100"
