FROM jenkins:1.642.2

RUN printf "%s\n"\
  "matrix-project:1.6" \
  "authentication-tokens:1.2" \
  "matrix-auth:1.1" \
  "credentials:1.25" \
  "script-security:1.13" \
  "external-monitor-job:1.4" \
  "durable-task:1.8" \
  "antisamy-markup-formatter:1.1" \
  "icon-shim:2.0.3" \
  "scm-api:1.0" \
  "ssh-credentials:1.11" \
  "ssh-slaves:1.9" \
  "git:2.4.2" \
  "git-client:1.19.6" \
  > /usr/share/jenkins/ref/plugins.txt \
 && /usr/local/bin/plugins.sh /usr/share/jenkins/ref/plugins.txt
USER root
RUN curl -sSL https://get.docker.com/builds/Linux/x86_64/docker-1.10.3 -o /bin/docker \
 && curl -L https://github.com/docker/compose/releases/download/1.6.2/docker-compose-Linux-x86_64\
    -o /bin/docker-compose \
 && chmod +x /bin/docker /bin/docker-compose
RUN adduser jenkins users
USER jenkins