version: '2'

services:
  server:
    build:
      context: ./server
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - server:/var/jenkins_home

volumes:
  server:
    driver: local
