version: '2'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - server:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
  node:
    build:
      context: .
      dockerfile: Dockerfile-node
    volumes:
      - node:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    ports:
      - 22/tcp

volumes:
  server:
    driver: local
  node:
    driver: local
