FROM jenkins:1.642.2

USER root
RUN curl -sSL https://get.docker.com/builds/Linux/x86_64/docker-1.10.3 -o /bin/docker \
 && curl -L https://github.com/docker/compose/releases/download/1.6.2/docker-compose-Linux-x86_64\
    -o /bin/docker-compose \
 && chmod +x /bin/docker /bin/docker-compose
RUN adduser jenkins users\
 && mkdir -p /jenkins\
 && chown jenkins:users /jenkins

ADD docker-compose.yml /jenkins/docker-compose.yml
ADD cli /usr/local/bin/cli
USER jenkins
WORKDIR /jenkins
ENTRYPOINT ["cli"]
CMD ["list"]
